# Generated by Django 5.0.1 on 2024-01-20 13:31

import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumini",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="alumini/")),
                ("passout_year", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=150)),
                (
                    "sub_heading",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("content", models.TextField()),
                ("slug", models.SlugField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=300, null=True)),
                (
                    "blog_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Blog/", verbose_name="Blog Image"
                    ),
                ),
                (
                    "cover_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Blog/", verbose_name="Blog Cover Image"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=300, null=True)),
                ("tag_line", models.CharField(blank=True, max_length=250, null=True)),
                ("flag_image", models.ImageField(upload_to="Country/")),
                (
                    "country_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Country/", verbose_name="Country Image"
                    ),
                ),
                (
                    "cover_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Country/", verbose_name="Country Cover Image"
                    ),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=300, null=True)),
                (
                    "course_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Course/", verbose_name="Course Image"
                    ),
                ),
                (
                    "cover_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Course/", verbose_name="Course Cover Image"
                    ),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                (
                    "current_education",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intended_study_abroad",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "area_of_study_interest",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "preferred_university_or_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "intended_course_of_study",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "language_proficiency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "standardized_tests_taken",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "financial_consideration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("message", models.CharField(blank=True, max_length=100, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "Enquiries",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=300, null=True)),
                (
                    "event_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Event/", verbose_name="Event Image"
                    ),
                ),
                (
                    "cover_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Event/", verbose_name="Event Cover Image"
                    ),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=250)),
                ("content", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name_plural": "Events",
            },
        ),
        migrations.CreateModel(
            name="EventEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("event", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Event Enquiries",
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name_plural": "FAQ's",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="gallery/", verbose_name="Gallery Image"
                    ),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name_plural": "Gallery",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=300, null=True)),
                (
                    "service_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Service/", verbose_name="Service Image"
                    ),
                ),
                (
                    "cover_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="Service/", verbose_name="Service Cover Image"
                    ),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                ("sub_content", models.TextField(blank=True, null=True)),
                ("content", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="ServiceEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("service", models.CharField(max_length=250)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Service Enquiries",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("designation", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="testimonials/", verbose_name="Testimonial Image"
                    ),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.CreateModel(
            name="CountryFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_title", models.CharField(max_length=200)),
                ("feature_image", models.ImageField(upload_to="CountryFeatur/")),
                ("feature_description", models.TextField()),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_course", models.CharField(max_length=300)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                    ),
                ),
            ],
        ),
    ]
