# Generated by Django 5.0 on 2023-12-29 08:39

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('country_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Country/', verbose_name='Country Image')),
                ('cover_image', versatileimagefield.fields.VersatileImageField(upload_to='Country/', verbose_name='Country Cover Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
