# Generated by Django 5.0 on 2023-12-29 08:50

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='tag_line',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='country_image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='Country/', verbose_name='Country Image'),
            preserve_default=False,
        ),
    ]
