# Generated by Django 5.0 on 2023-12-29 09:11

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_country_tag_line_alter_country_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('course_image', versatileimagefield.fields.VersatileImageField(upload_to='Course/', verbose_name='Course Image')),
                ('cover_image', versatileimagefield.fields.VersatileImageField(upload_to='Course/', verbose_name='Course Cover Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
