# Generated by Django 5.0 on 2023-12-29 09:16

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('service_image', versatileimagefield.fields.VersatileImageField(upload_to='Service/', verbose_name='Service Image')),
                ('cover_image', versatileimagefield.fields.VersatileImageField(upload_to='Service/', verbose_name='Service Cover Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
