# Generated by Django 5.0.1 on 2024-02-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_countryenquiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventenquiry",
            name="is_accepted",
        ),
        migrations.AddField(
            model_name="countryenquiry",
            name="country_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.country",
            ),
        ),
    ]
