# Generated by Django 5.0.1 on 2024-02-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_remove_eventenquiry_is_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceenquiry",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.service",
            ),
        ),
    ]
