# Generated by Django 5.0 on 2023-12-29 10:52

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_service_sub_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('blog_image', versatileimagefield.fields.VersatileImageField(upload_to='Blog/', verbose_name='Blog Image')),
                ('cover_image', versatileimagefield.fields.VersatileImageField(upload_to='Blog/', verbose_name='Blog Cover Image')),
                ('date', models.DateField(blank=True, null=True)),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
