# Generated by Django 5.0.1 on 2024-02-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_remove_serviceenquiry_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceenquiry",
            name="service_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.service",
            ),
        ),
    ]
