# Generated by Django 5.0 on 2023-12-29 11:23

import tinymce.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('event_image', versatileimagefield.fields.VersatileImageField(upload_to='Event/', verbose_name='Event Image')),
                ('cover_image', versatileimagefield.fields.VersatileImageField(upload_to='Event/', verbose_name='Event Cover Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=250)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
