# Generated by Django 5.0.1 on 2024-02-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_serviceenquiry_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceenquiry",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
