# Generated by Django 5.0.1 on 2024-02-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_serviceenquiry_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                (
                    "current_education",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intended_study_abroad",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "area_of_study_interest",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "preferred_university_or_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "intended_course_of_study",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "language_proficiency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "standardized_tests_taken",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "financial_consideration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("message", models.CharField(blank=True, max_length=100, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "course_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiries",
            },
        ),
        migrations.DeleteModel(
            name="Enquiry",
        ),
    ]
