# Generated by Django 5.0 on 2023-12-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_serviceenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('event', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Event Enquiries',
            },
        ),
    ]
